TF-680 wizaplace:translations:pull peut créer un fichier vide
wizaplace/wizaplace-front-bundle pull request #82
Opened 2021-08-05 10:03 UTC by rahma-saffar

## Checklist

- [ ] Changelog updated

2021-08-06 08:13 UTC, marwen-wiza requested changes

2021-08-06 08:13 UTC, marwen-wiza commented on src/Command/PullTranslationsCommand.php
> +    private function executeLocale(string $locale): string
stp sauvegarde le type de fonction en void, il ne faut pas le changer en string

2021-08-06 15:07 UTC, marwen-wiza approved these changes

2021-08-09 14:02 UTC, wizacedric requested changes
Merci de return un boolean plutôt qu'une string, et de faire un early return en cas d'erreur pour éviter d'avoir tout le code de la fonction dans un if.

2021-08-09 14:02 UTC, wizacedric commented on src/Command/PullTranslationsCommand.php
> +        if (!empty($xliffCatalog)) {
Inverser la condition pour sortir tout de suite en cas d'erreur

2021-08-09 14:02 UTC, wizacedric commented on src/Command/PullTranslationsCommand.php
> +    private function executeLocale(string $locale): string
```suggestion
    private function executeLocale(string $locale): bool
```

2021-08-09 15:04 UTC, marwen-wiza approved these changes

2021-08-11 08:56 UTC, marwen-wiza approved these changes

2021-10-18 12:50 UTC, merged